# Generated by Django 3.0.3 on 2020-02-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreList', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTab', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTarj', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('fkLista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBD.Lista')),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='fkTablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBD.Tablero'),
        ),
    ]
